name: checks
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: .

      - name: Get NodeJS version
        id: node-version
        uses: ./

      - name: Print version
        run: >-
          echo ${{ steps.node-version.outputs.version }}
          echo ${{ steps.node-version.outputs.major }}
          echo ${{ steps.node-version.outputs.minor }}
          echo ${{ steps.node-version.outputs.patch }}
